import {
  StyleSheet,
} from 'react-native';
import {
  v2ColorSystem,
} from '../../../../../styles/variables';

import { ResponsiveStyle } from '../../../../ResponsiveStyles';

const CounterofferSellerOverviewCardStyles: ResponsiveStyle = {
  defaultStyle: StyleSheet.create({
    firstTabButtonActiveStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: v2ColorSystem.black[100],
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginLeft: 0,
      marginRight: 16,
      paddingHorizontal: 0,
      textAlign: 'center',
      width: 'auto',
    },
    firstTabButtonStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'wrap',
      height: 48,
      justifyContent: 'center',
      marginLeft: 0,
      marginRight: 16,
      paddingHorizontal: 0,
      textAlign: 'center',
      width: 'auto',
    },
    overviewCardContainerStyle: {
      display: 'flex',
      paddingVertical: 32,
    },
    paginationBarContainerStyle: {
      marginTop: 'auto',
      paddingTop: 16,
    },
    tabButtonActiveStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomColor: v2ColorSystem.black[100],
      borderBottomWidth: 2,
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 16,
      textAlign: 'center',
      width: 'auto',
    },
    tabButtonDisabledStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 16,
      opacity: 0.5,
      textAlign: 'center',
      width: 'auto',
    },
    tabButtonStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 16,
      textAlign: 'center',
      width: 'auto',
    },
    tabPanelBodyStyle: {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      minHeight: 230,
      overflow: 'hidden',
      paddingVertical: 12,
    },
    tabPanelHeaderStyle: {
      borderBottomColor: v2ColorSystem.lightGray[100],
      borderBottomWidth: 1,
      display: 'flex',
      flexDirection: 'row',
      height: 48,
      paddingHorizontal: 48,
      width: '100%',
    },
    tabPanelInnerWrapperStyle: {
      height: 'auto',
      marginBottom: 'auto',
      width: '100%',
    },
    tabPanelLoadingWrapperStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'column',
      flexWrap: 'nowrap',
      height: 230,
      justifyContent: 'center',
    },
  }),
  mobileStyle: StyleSheet.create({
    tabPanelHeaderStyle: {
      borderBottomColor: v2ColorSystem.lightGray[100],
      borderBottomWidth: 1,
      display: 'flex',
      flexDirection: 'row',
      height: 48,
      paddingHorizontal: 26,
      width: '100%',
    },
    lotOfferHeaderCard: {
      alignContent: 'stretch',
      alignItems: 'flex-start',
      display: 'flex',
      flexDirection: 'column',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
    },
    lotOfferHeaderContainer: {
      paddingHorizontal: 16,
      width: '100%',
    },
  }),
}

export default CounterofferSellerOverviewCardStyles;
