import {
  StyleSheet,
} from 'react-native';
import {
  fontFamily,
  v2ColorSystem,
  v2FontSizes,
} from '../../../../../styles/variables';
import { ResponsiveStyle } from '../../../../ResponsiveStyles';

const CounterofferSellerOverviewCardStyles: ResponsiveStyle = {
  defaultStyle: StyleSheet.create({
    overviewCardContainerStyle: {
      display: 'flex',
      paddingVertical: 32,
    },
    tabPanelInnerWrapperStyle: {
      height: 'auto',
      width: '100%',
    },
    tabPanelHeaderStyle: {
      borderBottomColor: v2ColorSystem.lightGray[100],
      borderBottomWidth: 2,
      display: 'flex',
      flexDirection: 'row',
      height: 48,
      paddingHorizontal: 48,
      width: '100%',
    },
    tabPanelBodyStyle: {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      overflow: 'hidden',
    },
    tabPanelLoadingWrapperStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'column',
      flexWrap: 'nowrap',
      height: 230,
      justifyContent: 'center',
      marginTop: 32,
    },
    firstTabButtonStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginLeft: 0,
      marginRight: 8,
      paddingHorizontal: 8,
      textAlign: 'center',
      width: 'auto',
    },
    firstTabButtonActiveStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: v2ColorSystem.black[100],
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      height: 48,
      justifyContent: 'center',
      marginLeft: 0,
      marginRight: 8,
      paddingHorizontal: 8,
      textAlign: 'center',
      width: 'auto',
    },
    tabButtonActiveStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomColor: v2ColorSystem.black[100],
      borderBottomWidth: 2,
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      fontFamily: fontFamily.AreaNormal,
      fontSize: v2FontSizes.xSmall,
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 8,
      paddingHorizontal: 8,
      textAlign: 'center',
      width: 'auto',
    },
    tabButtonDisabledStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      fontFamily: fontFamily.AreaNormal,
      fontSize: v2FontSizes.xSmall,
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 8,
      opacity: 0.5,
      paddingHorizontal: 8,
      textAlign: 'center',
      width: 'auto',
    },
    tabButtonStyle: {
      alignContent: 'stretch',
      alignItems: 'center',
      borderColor: 'transparent',
      borderBottomWidth: 2,
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      fontFamily: fontFamily.AreaNormal,
      fontSize: v2FontSizes.xSmall,
      height: 48,
      justifyContent: 'center',
      marginHorizontal: 8,
      paddingHorizontal: 8,
      textAlign: 'center',
      width: 'auto',
    },
    lotOfferHeaderContainer: {
      borderBottomColor: v2ColorSystem.lightGray[100],
      borderBottomWidth: 1,
      paddingBottom: 10,
    },
  }),
  mobileStyle: StyleSheet.create({
    lotOfferHeaderCard: {
      alignContent: 'stretch',
      alignItems: 'flex-start',
      display: 'flex',
      flexDirection: 'column',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
    },
    lotOfferHeaderContainer: {
      width: '100%',
    },
    tabPanelHeaderStyle: {
      height: 16,
    },
  }),
}
export default CounterofferSellerOverviewCardStyles;
